### ISSUE TITLE
[FEAT]: Store all the course data into database

### ISSUE THREAD

**Issue by arv-anshul** [arv-anshul/pw-api#3]
Company (PW Skills) is removed the previous courses like DS 1.0, Web-Dev 1.0 and Java 1.0. That's why add the courses' data to a database.  
Choose any database cloud (MongoDB) or sqlite3.

### Steps to take

1. **Create schema** of all the different data and **draw ER Diagram** too.
2. **Make APIs** to retrieve data from database.
3. Also, new data must be get updated to database if any. (Like the **Live Courses** are always updating on the official website.)

**Comment by sandeep03mondal** [comment]
how to get the auth token in pw

**Comment by arv-anshul** [comment]
> how to get the auth token in pw

Here, @sandeep03mondal 

<img width="1680" alt="Screenshot 2023-07-12 at 16 55 07" src="https://github.com/arv-anshul/pw-api/assets/111767754/63011ca8-0b16-48ef-a5b2-d3c114ce3f19">

**Comment by sandeep03mondal** [comment]
<img width="597" alt="Untitled" src="https://github.com/arv-anshul/pw-api/assets/155039547/8d671e8b-3f1b-4d81-8e6f-96495773ef23">
showing this error

**Comment by arv-anshul** [comment]
Hey @sandeep03mondal , raise a [new issue](https://github.com/arv-anshul/pw-api/issues/new) for this we can discuss this there.

**Comment by arv-anshul** [comment]
😞 Project is not working well.
