### ISSUE TITLE
After running the app.py , and tried to login using auth token , but this is showing while I enter submit to login

### ISSUE THREAD

**Issue by sandeep03mondal** [arv-anshul/pw-api#4]
<img width="597" alt="img" src="https://github.com/arv-anshul/pw-api/assets/155039547/47983422-2724-4083-a901-1daf37015398">

**Comment by arv-anshul** [comment]
Hey @sandeep03mondal , I uses MacOs and this works fine there. I think you have to change the filename to tackle this error (this may not the right solution).

You can replace all (`<space>`, `-` and `:`) from filename and replace with (`_`) for this.

Example: `'2024-03-14 14:23:33.cookie'` > `'2024_03_14_14_23_33.cookie'`

**Comment by sandeep03mondal** [comment]
Hey @arv-anshul just let me sure , I just have to run the app.py and then do login using the auth token right ?

**Comment by arv-anshul** [comment]
> Hey @arv-anshul just let me sure , I just have to run the app.py and then do login using the auth token right ?

Yes.

**Comment by sandeep03mondal** [comment]
Will it make sense if I use virtual macos ventura OR monterey to run? @arv-anshul

**Comment by arv-anshul** [comment]
> Will it make sense if I use virtual macos ventura OR monterey ? @arv-anshul

Maybe.

**Comment by sandeep03mondal** [comment]
@arv-anshul could you please help,what needed to be modify in the python code that can run in Windows 11 ? , as there are many problems to install macOS in Windows System using Virtual  box !!!

**Comment by arv-anshul** [comment]
Hey @sandeep03mondal , sorry for late response.

**Solution:**

You have to change the dirname in this line in [`src/pw/credentials.py`](https://github.com/arv-anshul/pw-api/blob/e36148378fefe76fd42b889facc02401b2cbdd14/src/pw/credentials.py#L24).

> You can replace all (`<space>`, `-` and `:`) from filename and replace with (`_`) for this.

**Comment by arv-anshul** [comment]
This issue will close automatically in 7 days if there is no movement.

**Comment by sandeep03mondal** [comment]
> Hey @sandeep03mondal , sorry for late response.
> 
> **Solution:**
> 
> You have to change the dirname in this line in [`src/pw/credentials.py`](https://github.com/arv-anshul/pw-api/blob/e36148378fefe76fd42b889facc02401b2cbdd14/src/pw/credentials.py#L24).
> 
> > You can replace all (`<space>`, `-` and `:`) from filename and replace with (`_`) for this.

Can you help me to modify line 24 in credential.py ????

**Comment by arv-anshul** [comment]
> Can you help me to modify line 24 in credential.py ????

That's what I have told you [there](https://github.com/arv-anshul/pw-api/issues/4#issuecomment-2002960151) @sandeep03mondal . You have to just follow it.

Otherwise, wait I will create a pull request to solve that issue soon.

**Comment by arv-anshul** [comment]
Hey @sandeep03mondal , I have checked the course and I came to know that this project doesn't works with it now due some major changes in the website's APIs. Now they uses `/v2` APIs but I have but this with `/v1` APIs.

This should be updated for `/v2` APIs to work which is very hard to do. So I am not going to update this project anymore.

🫡 That's why I am closing this issue.

**Comment by sandeep03mondal** [comment]
Is there any other way to download the videos ? As I have 5 courses !!

**Comment by arv-anshul** [comment]
> Is there any other way to download the videos ? As I have 5 courses !!

This app doesn't download course videos at all. And I don't know how to do it.
